// Copyright (c) Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// @generated
// This file is @generated by prost-build.

/// Empty message for success responses
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}

/// Error response with type and message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorResponse {
    #[prost(string, tag = "1")]
    pub error_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}

/// Consensus state information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusState {
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    #[prost(uint64, tag = "2")]
    pub last_voted_round: u64,
    #[prost(uint64, tag = "3")]
    pub preferred_round: u64,
    /// BCS serialized Waypoint
    #[prost(bytes = "vec", tag = "4")]
    pub waypoint: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "5")]
    pub in_validator_set: bool,
}

/// Request for consensus state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ConsensusStateRequest {}

/// Response for consensus state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusStateResponse {
    #[prost(oneof = "consensus_state_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<consensus_state_response::Result>,
}
/// Nested message and enum types in `ConsensusStateResponse`.
pub mod consensus_state_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        State(super::ConsensusState),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to initialize with epoch change proof
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeRequest {
    /// BCS serialized EpochChangeProof
    #[prost(bytes = "vec", tag = "1")]
    pub epoch_change_proof: ::prost::alloc::vec::Vec<u8>,
}

/// Response for initialize
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeResponse {
    #[prost(oneof = "initialize_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<initialize_response::Result>,
}
/// Nested message and enum types in `InitializeResponse`.
pub mod initialize_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::Empty),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to sign a proposal
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignProposalRequest {
    /// BCS serialized BlockData
    #[prost(bytes = "vec", tag = "1")]
    pub block_data: ::prost::alloc::vec::Vec<u8>,
}

/// Response for sign proposal
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignProposalResponse {
    #[prost(oneof = "sign_proposal_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<sign_proposal_response::Result>,
}
/// Nested message and enum types in `SignProposalResponse`.
pub mod sign_proposal_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// BCS serialized bls12381::Signature
        #[prost(bytes, tag = "1")]
        Signature(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to sign timeout with QC
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignTimeoutWithQcRequest {
    /// BCS serialized TwoChainTimeout
    #[prost(bytes = "vec", tag = "1")]
    pub timeout: ::prost::alloc::vec::Vec<u8>,
    /// BCS serialized Option<TwoChainTimeoutCertificate>
    #[prost(bytes = "vec", optional, tag = "2")]
    pub timeout_cert: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// Response for sign timeout with QC
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignTimeoutWithQcResponse {
    #[prost(oneof = "sign_timeout_with_qc_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<sign_timeout_with_qc_response::Result>,
}
/// Nested message and enum types in `SignTimeoutWithQcResponse`.
pub mod sign_timeout_with_qc_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// BCS serialized bls12381::Signature
        #[prost(bytes, tag = "1")]
        Signature(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to construct and sign vote (2-chain)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstructAndSignVoteTwoChainRequest {
    /// BCS serialized VoteProposal
    #[prost(bytes = "vec", tag = "1")]
    pub vote_proposal: ::prost::alloc::vec::Vec<u8>,
    /// BCS serialized Option<TwoChainTimeoutCertificate>
    #[prost(bytes = "vec", optional, tag = "2")]
    pub timeout_cert: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}

/// Response for construct and sign vote (2-chain)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstructAndSignVoteTwoChainResponse {
    #[prost(oneof = "construct_and_sign_vote_two_chain_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<construct_and_sign_vote_two_chain_response::Result>,
}
/// Nested message and enum types in `ConstructAndSignVoteTwoChainResponse`.
pub mod construct_and_sign_vote_two_chain_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// BCS serialized Vote
        #[prost(bytes, tag = "1")]
        Vote(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to construct and sign order vote
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstructAndSignOrderVoteRequest {
    /// BCS serialized OrderVoteProposal
    #[prost(bytes = "vec", tag = "1")]
    pub order_vote_proposal: ::prost::alloc::vec::Vec<u8>,
}

/// Response for construct and sign order vote
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstructAndSignOrderVoteResponse {
    #[prost(oneof = "construct_and_sign_order_vote_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<construct_and_sign_order_vote_response::Result>,
}
/// Nested message and enum types in `ConstructAndSignOrderVoteResponse`.
pub mod construct_and_sign_order_vote_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// BCS serialized OrderVote
        #[prost(bytes, tag = "1")]
        OrderVote(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

/// Request to sign commit vote
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignCommitVoteRequest {
    /// BCS serialized LedgerInfoWithSignatures
    #[prost(bytes = "vec", tag = "1")]
    pub ledger_info: ::prost::alloc::vec::Vec<u8>,
    /// BCS serialized LedgerInfo
    #[prost(bytes = "vec", tag = "2")]
    pub new_ledger_info: ::prost::alloc::vec::Vec<u8>,
}

/// Response for sign commit vote
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignCommitVoteResponse {
    #[prost(oneof = "sign_commit_vote_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<sign_commit_vote_response::Result>,
}
/// Nested message and enum types in `SignCommitVoteResponse`.
pub mod sign_commit_vote_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// BCS serialized bls12381::Signature
        #[prost(bytes, tag = "1")]
        Signature(::prost::alloc::vec::Vec<u8>),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}

include!("aptos.safety_rules.v1.serde.rs");
include!("aptos.safety_rules.v1.tonic.rs");
// @@protoc_insertion_point(module)
